// ─── Icon system ──────────────────────────────────────────────────────────
// LGDesk_Master_Reference.md mandates Lucide React as the sole icon set
// (no Material Symbols, no MUI icons, no emoji-as-icon). This file is the
// single lookup table from the legacy Material-Symbol name (still used as
// the `name` prop everywhere via <Icon name="task_alt" />) to its closest
// Lucide component, so call sites never import lucide-react directly.
//
// Extend this map — do not fall back to emoji or MUI — whenever a new
// Material Symbol name shows up in a view that hasn't been migrated yet.
import {
  Home,
  CalendarRange,
  ListChecks,
  FolderOpen,
  NotebookPen,
  Calendar,
  Video,
  GitBranch,
  CalendarCheck,
  Contact,
  FolderKanban,
  Activity,
  FileBarChart,
  ClipboardList,
  Users,
  Table,
  Building2,
  FileText,
  Upload,
  Clock,
  CalendarX,
  CalendarOff,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowUpDown,
  ArrowRight,
  ArrowLeft,
  RefreshCw,
  Menu,
  Plus,
  Pencil,
  Trash2,
  X,
  Search,
  Bell,
  User,
  UserPlus,
  Settings,
  LogOut,
  LogIn,
  Filter,
  Download,
  Paperclip,
  Send,
  Check,
  CheckCircle2,
  XCircle,
  Info,
  HelpCircle,
  MoreVertical,
  MoreHorizontal,
  Save,
  Eye,
  EyeOff,
  Mail,
  Phone,
  MapPin,
  Briefcase,
  Cake,
  CalendarDays,
  Timer,
  Hourglass,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  LayoutDashboard,
  List,
  LayoutGrid,
  Star,
  Bookmark,
  Flag,
  AlertCircle,
  CircleAlert,
  Tag,
  FolderTree,
  File,
  Image,
  Printer,
  Share2,
  Link,
  Link2,
  Copy,
  ExternalLink,
  Maximize2,
  GripVertical,
  Inbox,
  Loader2,
  Sparkles,
  RotateCw,
  Megaphone,
  MessageCircle,
  MessageSquare,
  CalendarClock,
  CalendarCog,
  Plane,
  Folder,
  Coffee,
  Lock,
  UserCog,
  LocateFixed,
  Play,
  Minus,
  CornerDownRight,
  ScrollText,
  Trophy,
  Undo2,
  ChevronsDownUp,
  ChevronsUpDown,
  Webcam,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  // ── Base mapping — LGDesk_Master_Reference.md ────────────────────────
  home: Home,
  calendar_view_week: CalendarRange,
  task_alt: ListChecks,
  folder_open: FolderOpen,
  edit_note: NotebookPen,
  calendar_month: Calendar,
  video_call: Video,
  account_tree: GitBranch,
  event_available: CalendarCheck,
  contacts: Contact,
  checklist_rtl: ListChecks,
  checklist: ListChecks,
  folder_special: FolderKanban,
  monitoring: Activity,
  assessment: FileBarChart,
  pending_actions: ClipboardList,
  groups: Users,
  table_rows: Table,
  corporate_fare: Building2,
  description: FileText,
  upload_file: Upload,
  schedule: Clock,
  event_busy: CalendarX,
  warning: AlertTriangle,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  sort: ArrowUpDown,
  arrow_forward: ArrowRight,
  refresh: RefreshCw,
  menu: Menu,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  close: X,
  search: Search,
  notifications: Bell,
  notifications_none: Bell,
  person: User,
  person_add: UserPlus,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  chevron_down: ChevronDown,
  filter_list: Filter,
  download: Download,
  attach_file: Paperclip,
  send: Send,
  check: Check,
  check_circle: CheckCircle2,
  cancel: XCircle,
  info: Info,
  help: HelpCircle,
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  arrow_back: ArrowLeft,
  save: Save,
  visibility: Eye,
  visibility_off: EyeOff,
  mail: Mail,
  phone: Phone,
  location_on: MapPin,
  business: Briefcase,
  cake: Cake,
  today: CalendarDays,
  timer: Timer,
  hourglass_empty: Hourglass,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  bar_chart: BarChart3,
  pie_chart: PieChart,
  dashboard: LayoutDashboard,
  list: List,
  grid_view: LayoutGrid,
  star: Star,
  star_border: Star, // outline vs filled distinguished via strokeWidth/fill prop at call site
  bookmark: Bookmark,
  flag: Flag,
  priority_high: AlertCircle,
  label: Tag,
  category: FolderTree,
  insert_drive_file: File,
  image: Image,
  picture_as_pdf: FileText,
  print: Printer,
  share: Share2,
  link: Link,
  content_copy: Copy,
  open_in_new: ExternalLink,
  fullscreen: Maximize2,
  drag_indicator: GripVertical,
  inbox: Inbox, // empty-state default glyph

  // ── Extended mapping — additional Material Symbol names found in views
  //    that haven't been migrated to Lucide-native code yet ────────────
  add_link: Link2,
  auto_awesome: Sparkles,
  autorenew: RotateCw,
  campaign: Megaphone,
  chat: MessageCircle,
  chat_bubble_outline: MessageSquare,
  date_range: CalendarRange,
  edit_calendar: CalendarCog,
  error: CircleAlert,
  event: CalendarClock,
  fit_screen: Maximize2,
  flight: Plane,
  folder: Folder,
  local_cafe: Coffee,
  lock: Lock,
  manage_accounts: UserCog,
  my_location: LocateFixed,
  play_arrow: Play,
  progress_activity: Loader2, // loading-placeholder glyph — always rendered with a spin animation
  remove: Minus,
  subdirectory_arrow_right: CornerDownRight,
  summarize: ScrollText,
  trophy: Trophy,
  leaderboard: Trophy,
  undo: Undo2,
  unfold_less: ChevronsDownUp,
  unfold_more: ChevronsUpDown,
  video_camera_front: Webcam,
  videocam: Video,
  calendar_off: CalendarOff,
};

/** Fallback glyph for any name not (yet) present in ICON_MAP — never emoji, never MUI. */
export const DEFAULT_ICON: LucideIcon = HelpCircle;

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? DEFAULT_ICON;
}
